name: 'tag'
on:
  push:
    branches:
      - master
jobs:
  tag:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: christophebedard/tag-version-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_tag_prefix: 'v'
          version_regex: 'Version: ([0-9]+\.[0-9]+\.[0-9]+)'
          check_entire_commit_message: true